### ISSUE TITLE
Allow construction of LeptonTreeWeighter without secondary processes

### ISSUE THREAD

**Issue by austinschneider** [Harvard-Neutrino/LeptonInjector#23]
We should probably add another constructor that allows you to not pass a vector of secondary processes, equivalent to passing a vector of size 0.

This would need to be changed in the C++ and on the python side:
https://github.com/Harvard-Neutrino/LeptonInjector/blob/24e5d688f4ff23cf9e0922be9e2be6c7fd6e00a3/projects/injection/public/LeptonInjector/injection/TreeWeighter.h#L78
https://github.com/Harvard-Neutrino/LeptonInjector/blob/24e5d688f4ff23cf9e0922be9e2be6c7fd6e00a3/projects/injection/private/pybindings/injection.cxx#L95

**Comment by pweigel** [comment]
Added in https://github.com/Harvard-Neutrino/LeptonInjector/pull/27/commits/dfa9be272f8148f6363ee185b55cd4cf3e3ec6f9, might need some testing.
